language: node_js
node_js:
  - '11'
services:
  - docker
script:
  - make test
deploy:
  provider: npm
  email: exe-dealer@yandex.ru
  api_key:
    secure: NJN1RQ4TP1+XovRaInypO05lJQ/K2h/7tMXlUbl1i6xxlVmYePGMBwwdMqyUZUIwlyxv9rvV0P2Ju2tAPiUF0E3TZ4XtQw36iNns4O/hD/v+YulaO4+4HqrFArmc1UDFw9dKlt3tNt89W30ykCaT202D6XDppfnv99rRiVw/zbElC7DeOrZkaGqDJ5+nYln+EJQRTQJxMXpzFRdigOJFqTIH0cSdp55TnxYWQCSWtGfPJ/mYZmS1+JppEFvu8RGRbhjoFJq2spZEINM8++jtnoMywFraWIpxvpgW1w64io2JXxoVkB9XIX78eRSeCZGmZ+DqSepF5dO2xRnNgP077+vH4ACRUWuHL/mKXo1uk+M50xZ2TN5k0N8q6eZPKSQapCKoHyRStvZG9OMHUlqtyZha4P6Uqces4TlAlQoaj5cqt9ZnJ2+07HvGTBgJDJf6UsZCSskFHfR++ZqtMT8EIziWBZybeusG2VnqUs1hGDXaQnYA76OydTr0rxff2qIQW6FTrCWM8ADRv8S1ERpZKIRdbpJ+U6a1emUgE4CEWAmELgWz+QHiENuMkCeyT7iBvyeHHwHu+NcoZnoxWz8JexQ/WS2Y24W6+R0J07/hG/NxzO1bot83Gc3jB3qKd2jgmlIvqPoMgpPFSxFJscFydqfiklNSeDb8QPuX3lKAYmI=
  on:
    repo: kagis/pgwire
