language: node_js
node_js:
- '11'
deploy:
  provider: npm
  email: exe-dealer@yandex.ru
  api_key:
    secure: j6PssYOp3BcQgy8Tmv8af/07Y6K+peBE04rxPQspEYriwzy4LfZ08qpZQlBralW4dNG1h/snrm4uvlJaHOhB500XlUTQb1oSdHpLytBpGYwrLBdStl7O+hjaIQlL7mvmpr0MreGsxx3clYAzE+on340EBMzeGBTWd18rmL3kY/tTRloOSeGYy753t1Ows/vhASlbFWZ9FZfeHsEaFo++89hCk4x4u3gDRWRre95auB9zwFpYazg2cQU67+sL/BoY4/Ppxuq1+HFFGotJnAZE1Sn38LOQSyfO9cAzqHBs+EAskw2V6f19i6d4YM5BESSGhXZ93S5sJWgk2f6fJ05RZm61vm2jUeDACgffHIw+kMjo/R8jyfa0pEAe+dtUm1zER7L7NWZgJ2mDHCeAxfJ2MCIrrT7tjEBpxlE4df+m0HCQva1ZGr3eIbOS6j/0K8jNfmlKwAi9VNkQm6PJWC04m3T23rYgQT+71ba890d0bT+yjFK4/9aIEADpeBz6Ce4/tvdH4iL+YcT1yc5Y+RpaOiTUXRESkgJZppgKD2cFC4l5m9Z5pd8LUcdBBND21cjhYhN/2TKCq1OQxOws4zrcJKgdX8srqkdp78TvxufDpdcbTqWiyIlAlUw131/ZRxmReLdqw1owWzC9cb0ah+4kINLQ5EjNRsLZlXft8ODLZzw=
  on:
    repo: kagis/pgwire
