language: node_js
node_js:
  - '11'
services:
  - postgresql
addons:
  postgresql: '10'
before_script:
  - psql -c 'alter system set wal_level to logical;' -U postgres
deploy:
  provider: npm
  email: exe-dealer@yandex.ru
  api_key:
    secure: EQ/Bc1AbXJOSZuzeMuwbL89tvSlSAM+KeJ4yr2iR609QwqmrpV/Gt8ICJh7vvAC9xyPq46klqpd4pOpCvh+bt09WAmXnAOHpYpOzFTUWkJedEhGFVLeVDrBT5AGU6bZo55mBLEKO47UdZWtlcdb5yvg7aowF2alX4zks+p2NP37WURlVqRzadzdufyYLm1rz8/GFKRRSUCpyw2we3zSvm/fDl09zuIsHdkdZKICgHDZUYcytboYqGNSKTeIIskf7vI3bg6fRGMHtbAdjdLeqYtij0An8cdYspevQFg74qm64dL8c5QahWM35f4oVaRRTfuz2OuqvoVUbM5Icuy0yF8jAkbqxYGtHvbFmSNM0Ttx1x3lWKx+pabAVYrZD6mHghP7hViM+iIz3qCGVCK2NxZqe7KcQ/75Um++rygzEvofFWym6A+R9ERKCg+cvk2mCai/TUJNUbHQV1HbT9Ohf7uJ0MVnKI0oGhad7jyZivVDWWSvNwWgN8rZKE0aIumgclGJMTeAw6ydmXewBeNn7Xm0HCp4aANda0xqXuGyK2usmbHMd3uPDXXKYfC/YSH2mDxCw1SvS7Vxc1qW4Rij/rFxuLAzK1ovfUe9CmzLb2hQ2o2KFl35+LdifJ/89E6jEObmg10FiBk7oYJYqKYxVgMG2ru4TIVR81VW9jGRK8NU=
  on:
    # tags: true
    repo: kagis/pgwire
